"""create water readings table

Revision ID: 15975a4bbc04
Revises: 
Create Date: 2026-10-03 09:46:05.167029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15975a4bbc04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('turbidity_ntu', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('wqi_score', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=50), nullable=True),
    sa.Column('detected_contaminants', sa.JSON(), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_readings_device_id'), 'water_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_water_readings_id'), 'water_readings', ['id'], unique=False)
    op.create_index(op.f('ix_water_readings_timestamp'), 'water_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_readings_timestamp'), table_name='water_readings')
    op.drop_index(op.f('ix_water_readings_id'), table_name='water_readings')
    op.drop_index(op.f('ix_water_readings_device_id'), table_name='water_readings')
    op.drop_table('water_readings')
    # ### end Alembic commands ###
